version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/assignment2
      - JWT_SECRET=assignment2
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
